import pandas as pd #we're going to create a dataframe

#this code works on a single workbook with multiple sheets

#the file path
excel_file = r"C:\Users\**\BORDEREAUX DES SINISTRES AUTO ET RC XOL AU 31 12 2022 - Copy.xlsx"

#read the excel file
xls = pd.ExcelFile(excel_file)

#creates an empty dataframe
df_conso = pd.DataFrame()

#iterate through the sheets and append them to the dataframe
for sheet in xls.sheet_names :
    df = xls.parse(sheet_name=sheet) #reads every sheet in the file
    df['Sheet name']=sheet #creates a column at the end that contains the name of the source sheet
    df_conso = pd.concat([df_conso,df],ignore_index=True) #concatenate the dataframe generated by the loop and the consolidated df

with pd.ExcelWriter(excel_file,mode='a',engine='openpyxl') as writer : #open the excel file in the 'a' mode to append data to it and make sure it's colsed afterwards
    df_conso.to_excel(writer,sheet_name='Consolidated sheet',index=False) #convert the df to an excel file

print('Consolidation done!. New sheet "Consolidated sheet" has been created') #mission complete!





